version: '3.1'

services:
  db:
    image: postgres:13.10
    container_name: behave-django-db
    ports:
      - "5417:5432"
    environment:
      POSTGRES_DB: behave
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres